## 1. Exploración inicial para conocer la estructura del dataset, la calidad y el tipo de dato

**Objetivo:** entender qué ha funcionado hasta ahora en las campañas enviadas desde Brevo y convertirlo en aprendizaje accionable.

In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', None)

In [16]:
# Miramos el archivo

with open("data.csv", "r", encoding="utf-8", errors="replace") as f:
    for i in range(1, 10):
        print(i, f.readline().rstrip("\n"))
        
# Hay ';' y comillas raras

1 "From Date";"To Date"
2 22-10-2024;26-02-2026
3
4 "Campaign ID";"Campaign Name";"Name from";"Email from";"Sending date";Subject;Sent;"Non delivered";"Hard bounces";"Soft bounces";"Non delivered rate";Delivered;"Total opens";Opens;"Trackable open rate";"Apple MPP Opens";"Total clicked";Clicked;"Click rate";"Click-to-Open rate";Unsubscribed;"Unsubscription rate";"Delivered rate";"Hard Bounces rate";"Soft Bounces rate";Complaints;"Complaints rate"
5 5;"Resumen Webinar enGira!";enGira!;info@engira.art;04-12-2024;"Resumen Webinar enGira!";103;0;0;0;0%;103;247;87;84,47%;19;34;19;18,45%;27,94%;0;0%;100%;0%;0%;0;0%
6 6;"Artistas Catálogo";enGira!;info@engira.art;23-10-2024;"Participación Piloto enGira!";3;0;0;0;0%;3;13;3;100%;0;3;1;33,33%;33,33%;0;0%;100%;0%;0%;0;0%
7 8;"Artistas seleccionados";enGira!;info@engira.art;29-10-2024;"Artistas seleccionados";38;2;0;2;5,26%;36;773;44;100%;9;99;32;88,89%;91,43%;0;0%;94,74%;0%;5,26%;0;0%
8 10;"ARTISTAS TOOLKIT";enGira!;info@engira.art;28-10-2024;"Participación Piloto enGira​!";122;5;2;3;4,10%;117;974;134;100%;33;199;70;59,83%;69,31%;0;0%;95,90%;1,64%;2,46%;1;0,82%
9 12;Recordatorio;enGira!;info@engira.art;29-10-2024;"Participación Piloto enGira!";24;1;0;1;4,17%;23;214;27;100%;5;25;12;52,17%;54,55%;0;0%;95,83%;0%;4,17%;0;0%

In [17]:
#Expected 2 fields in line 4, saw 27
#significa que pandas está interpretando que el archivo tiene 2 columnas (por las primeras líneas), pero en la línea 4 aparece una fila con muchísimos separadores (o una línea “rota” por comillas / saltos de línea dentro de una celda).

# identificamos qué hay en las líneas problemáticas

from itertools import islice

with open("data.csv", "r", encoding="utf-8", errors="replace") as f:
    for i, line in enumerate(islice(f, 0, 10), start=1):
        print(f"{i:02d} | {line.rstrip()}")

01 | "From Date";"To Date"
02 | 22-10-2024;26-02-2026
03 |
04 | "Campaign ID";"Campaign Name";"Name from";"Email from";"Sending date";Subject;Sent;"Non delivered";"Hard bounces";"Soft bounces";"Non delivered rate";Delivered;"Total opens";Opens;"Trackable open rate";"Apple MPP Opens";"Total clicked";Clicked;"Click rate";"Click-to-Open rate";Unsubscribed;"Unsubscription rate";"Delivered rate";"Hard Bounces rate";"Soft Bounces rate";Complaints;"Complaints rate"
05 | 5;"Resumen Webinar enGira!";enGira!;info@engira.art;04-12-2024;"Resumen Webinar enGira!";103;0;0;0;0%;103;247;87;84,47%;19;34;19;18,45%;27,94%;0;0%;100%;0%;0%;0;0%
06 | 6;"Artistas Catálogo";enGira!;info@engira.art;23-10-2024;"Participación Piloto enGira!";3;0;0;0;0%;3;13;3;100%;0;3;1;33,33%;33,33%;0;0%;100%;0%;0%;0;0%
07 | 8;"Artistas seleccionados";enGira!;info@engira.art;29-10-2024;"Artistas seleccionados";38;2;0;2;5,26%;36;773;44;100%;9;99;32;88,89%;91,43%;0;0%;94,74%;0%;5,26%;0;0%
08 | 10;"ARTISTAS TOOLKIT";enGira!;info@engira.art;28-10-2024;"Participación Piloto enGira​!";122;5;2;3;4,10%;117;974;134;100%;33;199;70;59,83%;69,31%;0;0%;95,90%;1,64%;2,46%;1;0,82%
09 | 12;Recordatorio;enGira!;info@engira.art;29-10-2024;"Participación Piloto enGira!";24;1;0;1;4,17%;23;214;27;100%;5;25;12;52,17%;54,55%;0;0%;95,83%;0%;4,17%;0;0%
10 | 15;"Invitación Piloto enGira! Programadores";enGira!;info@engira.art;05-11-2024;"Programa Piloto enGira!";89;11;5;6;12,36%;78;12;10;12,82%;2;1;1;1,28%;12,50%;0;0%;87,64%;5,62%;6,74%;0;0%

In [18]:
df = pd.read_csv("data.csv", sep=";", engine="python", skiprows=3)

df.head()

,Campaign ID,Campaign Name,Name from,Email from,Sending date,Subject,Sent,Non delivered,Hard bounces,Soft bounces,Non delivered rate,Delivered,Total opens,Opens,Trackable open rate,Apple MPP Opens,Total clicked,Clicked,Click rate,Click-to-Open rate,Unsubscribed,Unsubscription rate,Delivered rate,Hard Bounces rate,Soft Bounces rate,Complaints,Complaints rate
0,5,Resumen Webinar enGira!,enGira!,info@engira.art,04-12-2024,Resumen Webinar enGira!,103,0,0,0,0%,103,247,87,"84,47%",19,34,19,"18,45%","27,94%",0,0%,100%,0%,0%,0,0%
1,6,Artistas Catálogo,enGira!,info@engira.art,23-10-2024,Participación Piloto enGira!,3,0,0,0,0%,3,13,3,100%,0,3,1,"33,33%","33,33%",0,0%,100%,0%,0%,0,0%
2,8,Artistas seleccionados,enGira!,info@engira.art,29-10-2024,Artistas seleccionados,38,2,0,2,"5,26%",36,773,44,100%,9,99,32,"88,89%","91,43%",0,0%,"94,74%",0%,"5,26%",0,0%
3,10,ARTISTAS TOOLKIT,enGira!,info@engira.art,28-10-2024,Participación Piloto enGira​!,122,5,2,3,"4,10%",117,974,134,100%,33,199,70,"59,83%","69,31%",0,0%,"95,90%","1,64%","2,46%",1,"0,82%"
4,12,Recordatorio,enGira!,info@engira.art,29-10-2024,Participación Piloto enGira!,24,1,0,1,"4,17%",23,214,27,100%,5,25,12,"52,17%","54,55%",0,0%,"95,83%",0%,"4,17%",0,0%

In [19]:
df.tail()

,Campaign ID,Campaign Name,Name from,Email from,Sending date,Subject,Sent,Non delivered,Hard bounces,Soft bounces,Non delivered rate,Delivered,Total opens,Opens,Trackable open rate,Apple MPP Opens,Total clicked,Clicked,Click rate,Click-to-Open rate,Unsubscribed,Unsubscription rate,Delivered rate,Hard Bounces rate,Soft Bounces rate,Complaints,Complaints rate
49,98,INVITACIÓN WEBINAR 26/11,enGira!,info@engira.art,22-11-2025,Invitación al Webinar enGira!,1449,24,4,20,"1,66%",1425,1708,852,"59,79%",320,8,8,"0,56%","1,50%",30,"2,11%","98,34%","0,28%","1,38%",0,0%
50,99,Grabación webinar y Programa de Acompañamiento,enGira!,info@engira.art,27-11-2025,Grabación Webinar y Plan de Acompañamiento,299,4,1,3,"1,34%",295,474,222,"75,25%",64,1,1,"0,34%","0,63%",1,"0,34%","98,66%","0,33%",1%,0,0%
51,100,Newsletter artistas Diciembre,enGira!,info@engira.art,09-12-2025,Últimas convocatorias del año,275,2,0,2,"0,73%",273,630,223,"81,68%",55,178,70,"25,64%","41,67%",0,0%,"99,27%",0%,"0,73%",0,0%
52,101,Newsletter artistas Diciembre_copy,enGira!,info@engira.art,08-01-2026,"Nuevo año, nuevas convocatorias",278,3,1,2,"1,08%",275,721,186,"67,64%",40,195,64,"23,27%","43,84%",1,"0,36%","98,92%","0,36%","0,72%",0,0%
53,102,Newsletter artistas Febrero,enGira!,info@engira.art,04-02-2026,Nuevas convocatorias,280,4,0,4,"1,43%",276,546,209,"75,72%",42,286,94,"34,06%","56,29%",0,0%,"98,57%",0%,"1,43%",0,0%

In [20]:
df.sample()

,Campaign ID,Campaign Name,Name from,Email from,Sending date,Subject,Sent,Non delivered,Hard bounces,Soft bounces,Non delivered rate,Delivered,Total opens,Opens,Trackable open rate,Apple MPP Opens,Total clicked,Clicked,Click rate,Click-to-Open rate,Unsubscribed,Unsubscription rate,Delivered rate,Hard Bounces rate,Soft Bounces rate,Complaints,Complaints rate
32,78,Presentes en dFeria,enGira!,info@engira.art,12-03-2025,Presentes en dFeria,229,5,3,2,"2,18%",224,327,153,"68,30%",54,14,7,"3,13%","7,07%",2,"0,89%","97,82%","1,31%","0,87%",0,0%

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 27 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Campaign ID          54 non-null     int64
 1   Campaign Name        54 non-null     str
 2   Name from            54 non-null     str
 3   Email from           54 non-null     str
 4   Sending date         54 non-null     str
 5   Subject              54 non-null     str
 6   Sent                 54 non-null     int64
 7   Non delivered        54 non-null     int64
 8   Hard bounces         54 non-null     int64
 9   Soft bounces         54 non-null     int64
 10  Non delivered rate   54 non-null     str
 11  Delivered            54 non-null     int64
 12  Total opens          54 non-null     int64
 13  Opens                54 non-null     int64
 14  Trackable open rate  54 non-null     str
 15  Apple MPP Opens      54 non-null     int64
 16  Total clicked        54 non-null     int64
 17  Clicked              54 non-null     int64
 18  Click rate           54 non-null     str
 19  Click-to-Open rate   54 non-null     str
 20  Unsubscribed         54 non-null     int64
 21  Unsubscription rate  54 non-null     str
 22  Delivered rate       54 non-null     str
 23  Hard Bounces rate    54 non-null     str
 24  Soft Bounces rate    54 non-null     str
 25  Complaints           54 non-null     int64
 26  Complaints rate      54 non-null     str
dtypes: int64(13), str(14)
memory usage: 11.5 KB

In [22]:
df.columns

Index(['Campaign ID', 'Campaign Name', 'Name from', 'Email from',
       'Sending date', 'Subject', 'Sent', 'Non delivered', 'Hard bounces',
       'Soft bounces', 'Non delivered rate', 'Delivered', 'Total opens',
       'Opens', 'Trackable open rate', 'Apple MPP Opens', 'Total clicked',
       'Clicked', 'Click rate', 'Click-to-Open rate', 'Unsubscribed',
       'Unsubscription rate', 'Delivered rate', 'Hard Bounces rate',
       'Soft Bounces rate', 'Complaints', 'Complaints rate'],
      dtype='str')

## ACCIONES DE LIMPIEZA

- normalizar nombres columnas
- transformar fecha date_to_time y separar mes, año y día
- crear nuevas columnas: 
    - tipo de público
        - artistas
        - programadores
    - tipo de campaña
        - convocatorias (keywords: convocatorias)
        - jornadas
        - ferias (keywords: dferia, madferia, mercartes, feria)
        - promocion (keywords: descubre, descobreix, funcionamiento,piloto, destacados)
        - formacion (keywords: webinar, demo, registro, catalogo, seleccionados, toolkit)

- eliminar columnas:
    - name_from
    - Email_from
    - Hard Bounces
    - Soft bounces
    - Non delivered
    - delivered
    - unsusbscribed
    - complaints